language: go

install:
  - wget -q https://raw.github.com/go-gl/testutils/master/travis-helper-functions.sh
  - source travis-helper-functions.sh
  - initialize
  - subtest-init go-gl/gl go-gl/examples

script:
  - go build -v
  - go test -v
  - subtest go-gl/gl go-gl/examples

after_script:
  - upload-to-imgur

after_failure: failure
after_error: failure

notifications:
  email:
    recipients:
      - p@pwaller.net
      - jimteeuwen@gmail.com
    on_success: change
    on_failure: always

