language: go

install:
  - wget -q https://raw.github.com/go-gl/testutils/master/travis-helper-functions.sh
  - source travis-helper-functions.sh
  - initialize
  - erl sudo eatmydata apt-get remove -qq libglew* || die "Failed to remove libglew-dev"
  - erl sudo eatmydata apt-get install -qq libgl1-mesa-dev libxrandr-dev libglu1-mesa-dev libx11-dev libxi-dev libxmu-dev || die "Failed to install dependencies"
  - wget -q "https://sourceforge.net/projects/glew/files/glew/1.10.0/glew-1.10.0.tgz/download" -O glew-1.10.0.tgz
  - tar xf glew-1.10.0.tgz
  - pushd glew-1.10.0
  - make
  - sudo make install
  - popd
  - subtest-init go-gl/gl go-gl/examples

script:
  - go build -v

after_script:
  - go test -v
  - upload-to-imgur
  - subtest go-gl/gl go-gl/examples

after_failure: failure
after_error: failure

notifications:
  email:
    recipients:
      - peter@pwaller.net
      - jimteeuwen@gmail.com
    on_success: change
    on_failure: always
