// Copyright 2012 The go-gl Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package gl

// #include "gl.h"
import "C"

const (
	BLEND_DST_ALPHA               = C.GL_BLEND_DST_ALPHA
	BLEND_DST_RGB                 = C.GL_BLEND_DST_RGB
	BLEND_SRC_ALPHA               = C.GL_BLEND_SRC_ALPHA
	BLEND_SRC_RGB                 = C.GL_BLEND_SRC_RGB
	COLOR_SUM                     = C.GL_COLOR_SUM
	COMPARE_R_TO_TEXTURE          = C.GL_COMPARE_R_TO_TEXTURE
	CURRENT_FOG_COORDINATE        = C.GL_CURRENT_FOG_COORDINATE
	CURRENT_SECONDARY_COLOR       = C.GL_CURRENT_SECONDARY_COLOR
	DECR_WRAP                     = C.GL_DECR_WRAP
	DEPTH_COMPONENT16             = C.GL_DEPTH_COMPONENT16
	DEPTH_COMPONENT24             = C.GL_DEPTH_COMPONENT24
	DEPTH_COMPONENT32             = C.GL_DEPTH_COMPONENT32
	DEPTH_TEXTURE_MODE            = C.GL_DEPTH_TEXTURE_MODE
	FOG_COORDINATE                = C.GL_FOG_COORDINATE
	FOG_COORDINATE_ARRAY          = C.GL_FOG_COORDINATE_ARRAY
	FOG_COORDINATE_ARRAY_POINTER  = C.GL_FOG_COORDINATE_ARRAY_POINTER
	FOG_COORDINATE_ARRAY_STRIDE   = C.GL_FOG_COORDINATE_ARRAY_STRIDE
	FOG_COORDINATE_ARRAY_TYPE     = C.GL_FOG_COORDINATE_ARRAY_TYPE
	FOG_COORDINATE_SOURCE         = C.GL_FOG_COORDINATE_SOURCE
	FRAGMENT_DEPTH                = C.GL_FRAGMENT_DEPTH
	GENERATE_MIPMAP               = C.GL_GENERATE_MIPMAP
	GENERATE_MIPMAP_HINT          = C.GL_GENERATE_MIPMAP_HINT
	INCR_WRAP                     = C.GL_INCR_WRAP
	MAX_TEXTURE_LOD_BIAS          = C.GL_MAX_TEXTURE_LOD_BIAS
	MIRRORED_REPEAT               = C.GL_MIRRORED_REPEAT
	POINT_DISTANCE_ATTENUATION    = C.GL_POINT_DISTANCE_ATTENUATION
	POINT_FADE_THRESHOLD_SIZE     = C.GL_POINT_FADE_THRESHOLD_SIZE
	POINT_SIZE_MAX                = C.GL_POINT_SIZE_MAX
	POINT_SIZE_MIN                = C.GL_POINT_SIZE_MIN
	SECONDARY_COLOR_ARRAY         = C.GL_SECONDARY_COLOR_ARRAY
	SECONDARY_COLOR_ARRAY_POINTER = C.GL_SECONDARY_COLOR_ARRAY_POINTER
	SECONDARY_COLOR_ARRAY_SIZE    = C.GL_SECONDARY_COLOR_ARRAY_SIZE
	SECONDARY_COLOR_ARRAY_STRIDE  = C.GL_SECONDARY_COLOR_ARRAY_STRIDE
	SECONDARY_COLOR_ARRAY_TYPE    = C.GL_SECONDARY_COLOR_ARRAY_TYPE
	TEXTURE_COMPARE_FUNC          = C.GL_TEXTURE_COMPARE_FUNC
	TEXTURE_COMPARE_MODE          = C.GL_TEXTURE_COMPARE_MODE
	TEXTURE_DEPTH_SIZE            = C.GL_TEXTURE_DEPTH_SIZE
	TEXTURE_FILTER_CONTROL        = C.GL_TEXTURE_FILTER_CONTROL
	TEXTURE_LOD_BIAS              = C.GL_TEXTURE_LOD_BIAS
)
