// Copyright 2012 The go-gl Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package gl

// #include "gl.h"
import "C"

const (
	ACTIVE_TEXTURE                 = C.GL_ACTIVE_TEXTURE
	ADD_SIGNED                     = C.GL_ADD_SIGNED
	CLAMP_TO_BORDER                = C.GL_CLAMP_TO_BORDER
	CLIENT_ACTIVE_TEXTURE          = C.GL_CLIENT_ACTIVE_TEXTURE
	COMBINE                        = C.GL_COMBINE
	COMBINE_ALPHA                  = C.GL_COMBINE_ALPHA
	COMBINE_RGB                    = C.GL_COMBINE_RGB
	COMPRESSED_ALPHA               = C.GL_COMPRESSED_ALPHA
	COMPRESSED_INTENSITY           = C.GL_COMPRESSED_INTENSITY
	COMPRESSED_LUMINANCE           = C.GL_COMPRESSED_LUMINANCE
	COMPRESSED_LUMINANCE_ALPHA     = C.GL_COMPRESSED_LUMINANCE_ALPHA
	COMPRESSED_RGB                 = C.GL_COMPRESSED_RGB
	COMPRESSED_RGBA                = C.GL_COMPRESSED_RGBA
	COMPRESSED_TEXTURE_FORMATS     = C.GL_COMPRESSED_TEXTURE_FORMATS
	CONSTANT                       = C.GL_CONSTANT
	DOT3_RGB                       = C.GL_DOT3_RGB
	DOT3_RGBA                      = C.GL_DOT3_RGBA
	INTERPOLATE                    = C.GL_INTERPOLATE
	MAX_CUBE_MAP_TEXTURE_SIZE      = C.GL_MAX_CUBE_MAP_TEXTURE_SIZE
	MAX_TEXTURE_UNITS              = C.GL_MAX_TEXTURE_UNITS
	MULTISAMPLE                    = C.GL_MULTISAMPLE
	MULTISAMPLE_BIT                = C.GL_MULTISAMPLE_BIT
	NORMAL_MAP                     = C.GL_NORMAL_MAP
	NUM_COMPRESSED_TEXTURE_FORMATS = C.GL_NUM_COMPRESSED_TEXTURE_FORMATS
	OPERAND0_ALPHA                 = C.GL_OPERAND0_ALPHA
	OPERAND0_RGB                   = C.GL_OPERAND0_RGB
	OPERAND1_ALPHA                 = C.GL_OPERAND1_ALPHA
	OPERAND1_RGB                   = C.GL_OPERAND1_RGB
	OPERAND2_ALPHA                 = C.GL_OPERAND2_ALPHA
	OPERAND2_RGB                   = C.GL_OPERAND2_RGB
	PREVIOUS                       = C.GL_PREVIOUS
	PRIMARY_COLOR                  = C.GL_PRIMARY_COLOR
	PROXY_TEXTURE_CUBE_MAP         = C.GL_PROXY_TEXTURE_CUBE_MAP
	REFLECTION_MAP                 = C.GL_REFLECTION_MAP
	RGB_SCALE                      = C.GL_RGB_SCALE
	SAMPLE_ALPHA_TO_COVERAGE       = C.GL_SAMPLE_ALPHA_TO_COVERAGE
	SAMPLE_ALPHA_TO_ONE            = C.GL_SAMPLE_ALPHA_TO_ONE
	SAMPLE_BUFFERS                 = C.GL_SAMPLE_BUFFERS
	SAMPLE_COVERAGE                = C.GL_SAMPLE_COVERAGE
	SAMPLE_COVERAGE_INVERT         = C.GL_SAMPLE_COVERAGE_INVERT
	SAMPLE_COVERAGE_VALUE          = C.GL_SAMPLE_COVERAGE_VALUE
	SAMPLES                        = C.GL_SAMPLES
	SOURCE0_ALPHA                  = C.GL_SOURCE0_ALPHA
	SOURCE0_RGB                    = C.GL_SOURCE0_RGB
	SOURCE1_ALPHA                  = C.GL_SOURCE1_ALPHA
	SOURCE1_RGB                    = C.GL_SOURCE1_RGB
	SOURCE2_ALPHA                  = C.GL_SOURCE2_ALPHA
	SOURCE2_RGB                    = C.GL_SOURCE2_RGB
	SUBTRACT                       = C.GL_SUBTRACT
	TEXTURE0                       = C.GL_TEXTURE0
	TEXTURE1                       = C.GL_TEXTURE1
	TEXTURE10                      = C.GL_TEXTURE10
	TEXTURE11                      = C.GL_TEXTURE11
	TEXTURE12                      = C.GL_TEXTURE12
	TEXTURE13                      = C.GL_TEXTURE13
	TEXTURE14                      = C.GL_TEXTURE14
	TEXTURE15                      = C.GL_TEXTURE15
	TEXTURE16                      = C.GL_TEXTURE16
	TEXTURE17                      = C.GL_TEXTURE17
	TEXTURE18                      = C.GL_TEXTURE18
	TEXTURE19                      = C.GL_TEXTURE19
	TEXTURE2                       = C.GL_TEXTURE2
	TEXTURE20                      = C.GL_TEXTURE20
	TEXTURE21                      = C.GL_TEXTURE21
	TEXTURE22                      = C.GL_TEXTURE22
	TEXTURE23                      = C.GL_TEXTURE23
	TEXTURE24                      = C.GL_TEXTURE24
	TEXTURE25                      = C.GL_TEXTURE25
	TEXTURE26                      = C.GL_TEXTURE26
	TEXTURE27                      = C.GL_TEXTURE27
	TEXTURE28                      = C.GL_TEXTURE28
	TEXTURE29                      = C.GL_TEXTURE29
	TEXTURE3                       = C.GL_TEXTURE3
	TEXTURE30                      = C.GL_TEXTURE30
	TEXTURE31                      = C.GL_TEXTURE31
	TEXTURE4                       = C.GL_TEXTURE4
	TEXTURE5                       = C.GL_TEXTURE5
	TEXTURE6                       = C.GL_TEXTURE6
	TEXTURE7                       = C.GL_TEXTURE7
	TEXTURE8                       = C.GL_TEXTURE8
	TEXTURE9                       = C.GL_TEXTURE9
	TEXTURE_BINDING_CUBE_MAP       = C.GL_TEXTURE_BINDING_CUBE_MAP
	TEXTURE_COMPRESSED             = C.GL_TEXTURE_COMPRESSED
	TEXTURE_COMPRESSED_IMAGE_SIZE  = C.GL_TEXTURE_COMPRESSED_IMAGE_SIZE
	TEXTURE_COMPRESSION_HINT       = C.GL_TEXTURE_COMPRESSION_HINT
	TEXTURE_CUBE_MAP               = C.GL_TEXTURE_CUBE_MAP
	TEXTURE_CUBE_MAP_NEGATIVE_X    = C.GL_TEXTURE_CUBE_MAP_NEGATIVE_X
	TEXTURE_CUBE_MAP_NEGATIVE_Y    = C.GL_TEXTURE_CUBE_MAP_NEGATIVE_Y
	TEXTURE_CUBE_MAP_NEGATIVE_Z    = C.GL_TEXTURE_CUBE_MAP_NEGATIVE_Z
	TEXTURE_CUBE_MAP_POSITIVE_X    = C.GL_TEXTURE_CUBE_MAP_POSITIVE_X
	TEXTURE_CUBE_MAP_POSITIVE_Y    = C.GL_TEXTURE_CUBE_MAP_POSITIVE_Y
	TEXTURE_CUBE_MAP_POSITIVE_Z    = C.GL_TEXTURE_CUBE_MAP_POSITIVE_Z
	TRANSPOSE_COLOR_MATRIX         = C.GL_TRANSPOSE_COLOR_MATRIX
	TRANSPOSE_MODELVIEW_MATRIX     = C.GL_TRANSPOSE_MODELVIEW_MATRIX
	TRANSPOSE_PROJECTION_MATRIX    = C.GL_TRANSPOSE_PROJECTION_MATRIX
	TRANSPOSE_TEXTURE_MATRIX       = C.GL_TRANSPOSE_TEXTURE_MATRIX
)
