// Copyright 2012 The go-gl Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package gl

// #include "gl.h"
import "C"

const (
	ACTIVE_ATTRIBUTE_MAX_LENGTH      = C.GL_ACTIVE_ATTRIBUTE_MAX_LENGTH
	ACTIVE_ATTRIBUTES                = C.GL_ACTIVE_ATTRIBUTES
	ACTIVE_UNIFORM_MAX_LENGTH        = C.GL_ACTIVE_UNIFORM_MAX_LENGTH
	ACTIVE_UNIFORMS                  = C.GL_ACTIVE_UNIFORMS
	ATTACHED_SHADERS                 = C.GL_ATTACHED_SHADERS
	BLEND_EQUATION_ALPHA             = C.GL_BLEND_EQUATION_ALPHA
	BLEND_EQUATION_RGB               = C.GL_BLEND_EQUATION_RGB
	BOOL                             = C.GL_BOOL
	BOOL_VEC2                        = C.GL_BOOL_VEC2
	BOOL_VEC3                        = C.GL_BOOL_VEC3
	BOOL_VEC4                        = C.GL_BOOL_VEC4
	COMPILE_STATUS                   = C.GL_COMPILE_STATUS
	COORD_REPLACE                    = C.GL_COORD_REPLACE
	CURRENT_PROGRAM                  = C.GL_CURRENT_PROGRAM
	CURRENT_VERTEX_ATTRIB            = C.GL_CURRENT_VERTEX_ATTRIB
	DELETE_STATUS                    = C.GL_DELETE_STATUS
	DRAW_BUFFER0                     = C.GL_DRAW_BUFFER0
	DRAW_BUFFER1                     = C.GL_DRAW_BUFFER1
	DRAW_BUFFER10                    = C.GL_DRAW_BUFFER10
	DRAW_BUFFER11                    = C.GL_DRAW_BUFFER11
	DRAW_BUFFER12                    = C.GL_DRAW_BUFFER12
	DRAW_BUFFER13                    = C.GL_DRAW_BUFFER13
	DRAW_BUFFER14                    = C.GL_DRAW_BUFFER14
	DRAW_BUFFER15                    = C.GL_DRAW_BUFFER15
	DRAW_BUFFER2                     = C.GL_DRAW_BUFFER2
	DRAW_BUFFER3                     = C.GL_DRAW_BUFFER3
	DRAW_BUFFER4                     = C.GL_DRAW_BUFFER4
	DRAW_BUFFER5                     = C.GL_DRAW_BUFFER5
	DRAW_BUFFER6                     = C.GL_DRAW_BUFFER6
	DRAW_BUFFER7                     = C.GL_DRAW_BUFFER7
	DRAW_BUFFER8                     = C.GL_DRAW_BUFFER8
	DRAW_BUFFER9                     = C.GL_DRAW_BUFFER9
	FLOAT_MAT2                       = C.GL_FLOAT_MAT2
	FLOAT_MAT3                       = C.GL_FLOAT_MAT3
	FLOAT_MAT4                       = C.GL_FLOAT_MAT4
	FLOAT_VEC2                       = C.GL_FLOAT_VEC2
	FLOAT_VEC3                       = C.GL_FLOAT_VEC3
	FLOAT_VEC4                       = C.GL_FLOAT_VEC4
	FRAGMENT_SHADER                  = C.GL_FRAGMENT_SHADER
	FRAGMENT_SHADER_DERIVATIVE_HINT  = C.GL_FRAGMENT_SHADER_DERIVATIVE_HINT
	INFO_LOG_LENGTH                  = C.GL_INFO_LOG_LENGTH
	INT_VEC2                         = C.GL_INT_VEC2
	INT_VEC3                         = C.GL_INT_VEC3
	INT_VEC4                         = C.GL_INT_VEC4
	LINK_STATUS                      = C.GL_LINK_STATUS
	LOWER_LEFT                       = C.GL_LOWER_LEFT
	MAX_COMBINED_TEXTURE_IMAGE_UNITS = C.GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS
	MAX_DRAW_BUFFERS                 = C.GL_MAX_DRAW_BUFFERS
	MAX_FRAGMENT_UNIFORM_COMPONENTS  = C.GL_MAX_FRAGMENT_UNIFORM_COMPONENTS
	MAX_TEXTURE_COORDS               = C.GL_MAX_TEXTURE_COORDS
	MAX_TEXTURE_IMAGE_UNITS          = C.GL_MAX_TEXTURE_IMAGE_UNITS
	MAX_VARYING_FLOATS               = C.GL_MAX_VARYING_FLOATS
	MAX_VERTEX_ATTRIBS               = C.GL_MAX_VERTEX_ATTRIBS
	MAX_VERTEX_TEXTURE_IMAGE_UNITS   = C.GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS
	MAX_VERTEX_UNIFORM_COMPONENTS    = C.GL_MAX_VERTEX_UNIFORM_COMPONENTS
	POINT_SPRITE                     = C.GL_POINT_SPRITE
	POINT_SPRITE_COORD_ORIGIN        = C.GL_POINT_SPRITE_COORD_ORIGIN
	SAMPLER_1D                       = C.GL_SAMPLER_1D
	SAMPLER_1D_SHADOW                = C.GL_SAMPLER_1D_SHADOW
	SAMPLER_2D                       = C.GL_SAMPLER_2D
	SAMPLER_2D_SHADOW                = C.GL_SAMPLER_2D_SHADOW
	SAMPLER_3D                       = C.GL_SAMPLER_3D
	SAMPLER_CUBE                     = C.GL_SAMPLER_CUBE
	SHADER_SOURCE_LENGTH             = C.GL_SHADER_SOURCE_LENGTH
	SHADER_TYPE                      = C.GL_SHADER_TYPE
	SHADING_LANGUAGE_VERSION         = C.GL_SHADING_LANGUAGE_VERSION
	STENCIL_BACK_FAIL                = C.GL_STENCIL_BACK_FAIL
	STENCIL_BACK_FUNC                = C.GL_STENCIL_BACK_FUNC
	STENCIL_BACK_PASS_DEPTH_FAIL     = C.GL_STENCIL_BACK_PASS_DEPTH_FAIL
	STENCIL_BACK_PASS_DEPTH_PASS     = C.GL_STENCIL_BACK_PASS_DEPTH_PASS
	STENCIL_BACK_REF                 = C.GL_STENCIL_BACK_REF
	STENCIL_BACK_VALUE_MASK          = C.GL_STENCIL_BACK_VALUE_MASK
	STENCIL_BACK_WRITEMASK           = C.GL_STENCIL_BACK_WRITEMASK
	UPPER_LEFT                       = C.GL_UPPER_LEFT
	VALIDATE_STATUS                  = C.GL_VALIDATE_STATUS
	VERTEX_ATTRIB_ARRAY_ENABLED      = C.GL_VERTEX_ATTRIB_ARRAY_ENABLED
	VERTEX_ATTRIB_ARRAY_NORMALIZED   = C.GL_VERTEX_ATTRIB_ARRAY_NORMALIZED
	VERTEX_ATTRIB_ARRAY_POINTER      = C.GL_VERTEX_ATTRIB_ARRAY_POINTER
	VERTEX_ATTRIB_ARRAY_SIZE         = C.GL_VERTEX_ATTRIB_ARRAY_SIZE
	VERTEX_ATTRIB_ARRAY_STRIDE       = C.GL_VERTEX_ATTRIB_ARRAY_STRIDE
	VERTEX_ATTRIB_ARRAY_TYPE         = C.GL_VERTEX_ATTRIB_ARRAY_TYPE
	VERTEX_PROGRAM_POINT_SIZE        = C.GL_VERTEX_PROGRAM_POINT_SIZE
	VERTEX_PROGRAM_TWO_SIDE          = C.GL_VERTEX_PROGRAM_TWO_SIDE
	VERTEX_SHADER                    = C.GL_VERTEX_SHADER
)
