// Copyright 2012 The go-gl Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package gl

// #include "gl.h"
import "C"

const (
	INT_SAMPLER_CUBE_MAP_ARRAY            = C.GL_INT_SAMPLER_CUBE_MAP_ARRAY
	MAX_PROGRAM_TEXTURE_GATHER_COMPONENTS = C.GL_MAX_PROGRAM_TEXTURE_GATHER_COMPONENTS
	MAX_PROGRAM_TEXTURE_GATHER_OFFSET     = C.GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET
	MIN_PROGRAM_TEXTURE_GATHER_OFFSET     = C.GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET
	MIN_SAMPLE_SHADING_VALUE              = C.GL_MIN_SAMPLE_SHADING_VALUE
	PROXY_TEXTURE_CUBE_MAP_ARRAY          = C.GL_PROXY_TEXTURE_CUBE_MAP_ARRAY
	SAMPLE_SHADING                        = C.GL_SAMPLE_SHADING
	SAMPLER_CUBE_MAP_ARRAY                = C.GL_SAMPLER_CUBE_MAP_ARRAY
	SAMPLER_CUBE_MAP_ARRAY_SHADOW         = C.GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW
	TEXTURE_BINDING_CUBE_MAP_ARRAY        = C.GL_TEXTURE_BINDING_CUBE_MAP_ARRAY
	TEXTURE_CUBE_MAP_ARRAY                = C.GL_TEXTURE_CUBE_MAP_ARRAY
	UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY   = C.GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY
)
